# Generated by Django 2.2.2 on 2019-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('CourseID', models.IntegerField()),
                ('CourseNumber', models.CharField(max_length=128)),
                ('CourseName', models.CharField(max_length=128)),
                ('CourseDescription', models.CharField(max_length=8192)),
                ('CourseCredit', models.CharField(max_length=3)),
                ('CourseEquivalenceNonOC', models.CharField(max_length=128)),
                ('InstitutionID', models.IntegerField(choices=[(1, 'Olivet'), (2, 'KCC'), (3, 'Military'), (0, 'Unknown')], default=0)),
                ('ReviewerID', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
