# Generated by Django 2.2.2 on 2019-06-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseEquivalenceNonOC',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
