# Generated by Django 2.2.2 on 2019-06-11 14:51

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('dbadmin', '0002_auto_20190610_1806'),
    ]

    operations = [
    ]
