# Generated by Django 2.2.2 on 2019-06-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbadmin', '0003_auto_20190611_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('OutcomeID', models.IntegerField()),
                ('OutcomeDescription', models.CharField(max_length=1024)),
                ('CourseNumber', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('ReviewerID', models.IntegerField()),
                ('ReviewerName', models.CharField(max_length=128)),
                ('ReviewerPhone', models.CharField(max_length=16)),
                ('ReviewerEmail', models.CharField(max_length=128)),
                ('ReviewerDepartment', models.CharField(max_length=8)),
            ],
        ),
    ]
