# Generated by Django 2.2.2 on 2019-06-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbadmin', '0005_auto_20190612_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('InstitutionID', models.IntegerField()),
                ('InstitutionName', models.CharField(max_length=128)),
                ('InstitutionAddress', models.CharField(max_length=256)),
                ('InstitutionCity', models.CharField(max_length=128)),
                ('InstitutionState', models.CharField(max_length=32)),
                ('InstitutionZipcode', models.CharField(max_length=16)),
                ('InstitutionWebSite', models.CharField(max_length=256)),
            ],
        ),
    ]
