# Generated by Django 2.2.2 on 2019-06-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbadmin', '0008_auto_20190625_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
